#uses the json file metadata file that describes how the template should be presented to users when they're creating a workflow.
#  Note
# The metadata file must have the same name as the workflow file. Instead of the .yml extension, it must be appended with .properties.json. 
# For example, a file named octo-organization-ci.properties.json contains the metadata for the workflow file named octo-organization-ci.yml.
# Both files must be placed in a public .github repository and in a directory named workflow-templates. 
# You might have to create these if they don't already exist in your organization.

# could not call/run template since my account had no organization
name: Octo Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization
