on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: true
        default: '14'
        type: string
    secrets:
      NODE_AUTH_TOKEN:
        description: 'Node authentication token'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}

    - name: Print 
      run: echo "Hurray! I was able to call my reusable template"
# Below throws an error because this is not a node repo with package.json or package-list.json    
    # - name: Install dependencies
    #   run: npm install
      
    # - name: Run tests
    #   run: npm test
