name: CI

on:
  workflow_dispatch:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-template:
    uses: ./.github/workflows/reusable-template.yml
    with:
      node-version: '16'
    secrets:
      NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
